### ISSUE TITLE
Q) Didn't you consider 'threshold' as hyperparameter?

### ISSUE THREAD

**Issue by TaeniKim** [NahuelCostaCortez/Remaining-Useful-Life-Estimation-Variational#2]
Most papers use "125" as the default threshold value, and your paper is the same.
In my experiment, the threshold value seems to be a major factor in model performance.
I would like to ask you why you fixed 125 or if you have any experience in evaluating changes.
I would appreciate it if you could give me an opinion.
thank U.

**Comment by NahuelCostaCortez** [comment]
Hi TaeniKim,

125 was chosen as the maximum RUL in order to make fair comparisons with respect to other works as they used the same value. I did not consider this value as a hyper parameter because the model would learn to maximize the metric, not actually learn the degradation. My intuition is that the smaller the limit, the better the metric will be because it will be avoiding prediction errors at higher values.

**Comment by TaeniKim** [comment]
As you said, it would be better to compare the evaluation based on the experimental criteria of most authors to improve performance in high RUL.
Thank you for your opinion.
